### 과목명: 딥러닝및실습 hw1_1
##### 실습자: 2017136063 여승준

# a_tensor_initialization.py

In [37]:
#pytorch's main package which is a tensor library
import torch

In [38]:
t1 = torch.Tensor([1,2,3], device='cpu')
'''
torch.'T'ensor = torch.FloatTensor이고,
torch.'t'ensor = torch.LongTensor임. (생성자)

미분에 관한 연산엔진을 내장하는 
requires_grad 옵션은 , default = False
'''
print(t1.dtype)         # torch.float32
print(t1.device)        # >>> cpu
print(t1.requires_grad) # >>>False
print(t1.size())        # torch.Size([3])
print(t1.shape)         # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [39]:
# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda')) #>>> error for me

# or you can use shorthand (내 컴퓨터의 경우 t1.cuda()가 먹지 않았다.)
#t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

In [40]:
print("#" * 50, 1)

################################################## 1


In [41]:
# torch.tensor function
t2 = torch.tensor([1,2,3], device='cpu')
print(t2.dtype) 
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [42]:
# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

################################################## 2


### 텐서의 shape(=size)를 구하는 법, dimension을 구할 줄 알아야 함 

In [43]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)
assert a1.shape == torch.Size([])

torch.Size([]) 0


In [44]:
a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)
print(a2.dtype)
assert a2.dtype == torch.int64

a2_float = torch.as_tensor(a2, dtype=torch.float)
print(a2_float.dtype)

torch.Size([1]) 1
torch.int64
torch.float32


In [45]:
a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)
assert a3.shape==torch.Size([5])
assert a3.ndim == 1

torch.Size([5]) 1


In [46]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [47]:
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [48]:
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [49]:
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [50]:
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [51]:
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [52]:
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)
assert a9.shape == torch.Size([3,1,2,3,1]) and a9.ndim==5

torch.Size([3, 1, 2, 3, 1]) 5


In [53]:
a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

torch.Size([4, 1, 5]) 3


In [54]:
# a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
# ])

# 3번째 dimension이 3이어야 했는데 [4,5]로 2개짜리 행이 있어서 ValueError

dfdf


# b_tensor_initialization_copy.py

In [55]:
import torch
import numpy as np

In [56]:
l1 = [1,2,3]
t1 = torch.Tensor(l1)
print(l1, t1, type(l1), t1.dtype, sep="\n")

[1, 2, 3]
tensor([1., 2., 3.])
<class 'list'>
torch.float32


In [57]:
l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

In [58]:
assert t1.dtype==torch.float32 and t2.dtype==torch.long
print(t3)
print(t3.dtype, t3.ndim, sep="\n")

tensor([1, 2, 3])
torch.int64
1


In [59]:
#l1[0] = 100
l2[0] = 100
#l3[0] = 100
print(l1, l2, l3)
print(id(l1[0]), id(l2[0]), id(l3[0]))
print(id(t1[0]), id(t2[0]), id(t3[0]))

[1, 2, 3] [100, 2, 3] [1, 2, 3]
2723154493680 2723154496848 2723154493680
2723898701072 2723233919632 2723233919632


In [60]:
print("#" * 50)

##################################################


### t4는 왜 dtype이 출력되지 않을까? 
torch.Tensor(list)의 경우엔 dtype=torch.float32가 출력되지 않는가 봄

In [61]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4, t4.dtype)
print(t5)
print(t6)

tensor([1., 2., 3.]) torch.float32
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


# c_tensor_initialization_constant_values.py

In [62]:
import torch

t1 = torch.ones(size=(5,))
t1_another = torch.ones(5)
t1_like = torch.ones_like(t1)
print(t1, t1_another, t1_like, sep="\n")

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [63]:
t2 = torch.zeros(size=(5,))
t2_another = torch.zeros([5,]) #size 매개변수로 list, tuple 등 가능
t2_another2 = torch.zeros(5)
t2_like = torch.zeros_like(t2)
print(t2, t2_another, t2_another2, t2_like, sep="\n")

tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])


In [64]:
t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(t3) # 0. 이 아니라 0에 근사한 소수가 나옴 
t3_ano = torch.empty((4,3))
print(t3,t3_like, t3_ano, sep="\n")

tensor([0., 0., 0., 0.])
tensor([3.5873e-43,        nan, 3.2973e-04, 4.5909e-41])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [65]:
eye = torch.eye(4)
print(eye)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


# d_tensor_initialization_random_values.py

torch.randint(low, high, size) : return x (10<=x<20)
torch.rand(size) :  0과 1 사이의 균등 분포 (각 소수 저마다 나올 확률이 모두 같음)
torch.randn(size) : 0,1 사이의 표준 정규 분포 (평균 0, 표준편차 1)
torch.normal(mean, std, size, ...) : (사용자 정의)정규분포 ---> 평균과 표준편차 직접 정의
torch.linspace(start, end, steps, ...) : 정해진 step수 만큼 동일 간격의 수를 유지하는 1d tensor를 리턴.
torch.arange(start=0, end, steps=1, ...) : 정해진 구간 사이의 값에 대해, start 부터 정해진 step씩 떨어진 모든 값을 1d 텐서로 반환

In [66]:
t1 = torch.randint(low=10, high=20, size=(2,4))
t2 = torch.rand(2,4)
t3 = torch.randn(2,4)
t4 = torch.normal(5, 1, size=(3,4))
t5 = torch.linspace(0,4,4)
t6 = torch.arange(1, 5, 0.5)
print(t1, t2, t3, t4, t5, t6, sep="\n")

tensor([[17, 10, 11, 10],
        [11, 16, 17, 15]])
tensor([[0.4185, 0.5007, 0.6236, 0.7559],
        [0.3635, 0.3987, 0.5057, 0.7642]])
tensor([[ 0.6856,  0.4161, -2.7180, -0.8691],
        [-0.8015, -0.3534, -0.9983, -0.3400]])
tensor([[3.2105, 4.1356, 5.6637, 4.9325],
        [4.2455, 5.2857, 5.2271, 3.6281],
        [4.9551, 6.4487, 5.8539, 3.0533]])
tensor([0.0000, 1.3333, 2.6667, 4.0000])
tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])


In [67]:
print("#" * 30)

##############################


<b>torch.manual_seed(seed) : random number generator를 고정된 값으로 세팅함으로써, 다음번 호출에도 똑같은 결과가 나오도록 해줄 수 있음.

In [68]:
torch.manual_seed(1729)
rnd1 = torch.rand(2,3)
rnd2 = torch.rand(2,3)
print(rnd1, rnd2, sep="\n")

print( "\n", "--"*20,  "\n", "reset", "\n")

torch.manual_seed(1729)
rnd1_re = torch.rand(2,3)
rnd2_re = torch.rand(2,3)
print(rnd1_re, rnd2_re, sep="\n")

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

 ---------------------------------------- 
 reset 

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion.py

### 주로 사용하는 torch.dtype ==> tensor.float32, int64 임.

- torch.ones() 함수에 dtype 명시해주기
- [tensor].to(dtype) 

In [69]:
import torch

a = torch.ones(2,3)
print(a, a.dtype)

a_zeros = a.to(torch.int64)
print(a_zeros)

a_new = torch.ones(size=(2,3), dtype=torch.int8)
print(a_new)

a_pos = a_new.to(torch.int16)
print(a_pos)


print("\n", '*' * 50, "\n")

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)


print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double) # 0,1 사이의 값으로 채워진, size 5인 double형의 tensor
short_g = double_f.to(torch.short)
multiply = double_f * short_g
print(f"double_f: {double_f}\nshort_g: {short_g}")
print(multiply) # 더 큰 자료형으로 형변환 되는 듯


tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

 ************************************************** 

torch.float64
torch.int16
double_f: tensor([0.9021, 0.3627, 0.9826, 0.5431, 0.1075], dtype=torch.float64)
short_g: tensor([0, 0, 0, 0, 0], dtype=torch.int16)
tensor([0., 0., 0., 0., 0.], dtype=torch.float64)


# f_tensor_operations.py
Element-wise operations : 사이즈가 같은 두 텐서끼리의 add, sub, mul, div 연산은 각 자리수끼리의 연산결과를 리턴한다.

In [70]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])



************
# g_tensor_operations_mm.py
torch.mul(input, other): '브로드캐스팅'을 동반한 element-wise multiplications
torch.dot(input, other) : computes the dot product of two 1D tensors
torch.mm(input, other): matrix multiplication without 'broadcasting'
torch.bmm(input, other): performs a batch matrix multiplication without broadcasting


<br><br>
##### dot 연산
dot() 연산은 만약 A = [a₁, a₂, a₃, ..., aₙ]과 B = [b₁, b₂, b₃, ..., bₙ]이라면,
A와 B의 도트 곱은 다음과 같이 계산됩니다:
A · B = a₁b₁ + a₂b₂ + a₃b₃ + ... + aₙbₙ

<br><br>
##### bmm:batch에 대하여
특별히 bmm()에 들어오는 tensor는 {batch-size X n X m}, {batch-size X m X p} 형식이어야만 한다.  


In [71]:
''' 

- torch.mul() 연산에 대하여 -
ing2 = torch.ones(size=(2,2)) * 2 로 선언했을때도 브로드캐스팅이 되어 
ing1과 mul() 연산이 가능할 줄 알았는데 그렇지 않았다.

'''


ing1 = torch.rand(size=(2,4)) * 10
ing2 = torch.ones(size=(1,4)) * 2
#ing2 = torch.ones(size=(2,2)) * 2 # 는 mul() 불가능함
print(ing1, ing2, sep="\n")

mul_scalar = torch.mul(ing1,2)
print(mul_scalar)

mul_vec = torch.mul(ing1, ing2) # Element-wise 연산이라서, 자연히 
print(mul_vec)
t1 = torch.mul

tensor([[7.4807, 0.3612, 5.0622, 8.4695],
        [2.5884, 2.7065, 4.1148, 6.8386]])
tensor([[2., 2., 2., 2.]])
tensor([[14.9614,  0.7224, 10.1244, 16.9389],
        [ 5.1768,  5.4131,  8.2296, 13.6772]])
tensor([[14.9614,  0.7224, 10.1244, 16.9389],
        [ 5.1768,  5.4131,  8.2296, 13.6772]])


In [72]:
'''
dot()연산에 대해

dot() 연산은 만약 A = [a₁, a₂, a₃, …, aₙ]과 B = [b₁, b₂, b₃, …, bₙ]이라면, A와 B의 도트 곱은 다음과 같이 계산됩니다: A · B = a₁b₁ + a₂b₂ + a₃b₃ + … + aₙbₙ

broadcasting : X
'''


int1 = torch.arange(1,10, 2) # [1,3,5,7,9]
int2 = torch.ones(size=(5,), dtype=torch.int64) * 2
int_brd = torch.ones(size=(1,), dtype=torch.int64) * 2
print(int1, int2, sep="\n")

print()
dot = torch.dot(int1, int2)
print(dot, int1, int2, sep="\n")

'''
print("dot() 연산 broadcasting -test")
dot = torch.dot(int1, int_brd)
print(dot, int1, int_brd, sep="\n")
'''

print("-"*30)
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

tensor([1, 3, 5, 7, 9])
tensor([2, 2, 2, 2, 2])

tensor(50)
tensor([1, 3, 5, 7, 9])
tensor([2, 2, 2, 2, 2])
------------------------------
tensor(7) torch.Size([])


In [73]:
'''
torch.mm() 연산은 2D Tensor끼리의 연산을 지원하며, 브로드캐스팅이 없다.
(nXm, mXp)이면 결과로 (nXp)가 나온다. 
'''

t2 = torch.randn(2, 4) # randn() 함수는 0,1 사이의 표준정규분포를 따른다.
# t2 = torch.randn(2, 2) # 브로드캐스팅 안됌
t3 = torch.randn(4, 2)
t4 = torch.mm(t2, t3)
print(t2, t3, t4, t4.size(), sep="\n")

tensor([[-1.1860, -0.4872, -1.9286, -1.1155],
        [ 2.2702,  0.1513, -0.6572,  0.0337]])
tensor([[ 0.5095, -1.2934],
        [ 0.0326, -1.9171],
        [ 1.1867, -1.0347],
        [ 1.6391, -0.5500]])
tensor([[-4.7372,  5.0770],
        [ 0.4370, -2.5649]])
torch.Size([2, 2])


In [74]:
'''torch.bmm()'''

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
# print(t5, t6, sep="\n")
t7 = torch.bmm(t5, t6)
print(t7.size())

torch.Size([10, 3, 5])


# h_tensor_operations_matmul.py

matmul과 mm의 차이

- torch.matmul(): 이 함수는 행렬 곱셈뿐만 아니라 다양한 다차원 배열 간의 곱셈을 다룰 수 있는 범용적인 행렬 곱셈 함수입니다. 따라서 2D 행렬뿐만 아니라 고차원의 텐서에 대해서도 작동합니다. torch.matmul()은 <b>브로드캐스팅 규칙을 따르며, 고차원 텐서에 대해서도 올바르게 작동하도록 설계되었습니다.</b>
- torch.mm(): 이 함수는 <b>오직 2D 행렬 간의 곱셈</b>만을 수행하는 함수입니다. 따라서 두 개의 2D 행렬을 인자로 받아야 하며, 두 행렬의 내적을 계산합니다. 고차원 텐서에 대해서는 작동하지 않습니다.

마지막 차원의 size가 맞아야 하고, 그 두 벡터끼리 내적의 결과로 스칼라가 나오기 때문에 결과값의 차원은 마지막 차원을 뺀 나머지 차원만 남는다.
예) matmul(5x3x4, 4) ==> (5x3)

In [75]:
# vector x vector: dot product
t1 = torch.randn(3) # 1d
t2 = torch.randn(3) # 1d
print(t1, t2, t1.size())
print()

# dot 연산 확인
cnt = torch.tensor(list(map(lambda x,y : x*y , t1,t2)))
res = sum(cnt) 
print(f'cnt: {cnt}, res: {res}')

print(torch.matmul(t1, t2))
print(torch.matmul(t1, t2).size())  # torch.Size([])

tensor([-1.8802, -2.2156,  0.3741]) tensor([-0.2782,  1.0238,  0.0738]) torch.Size([3])

cnt: tensor([ 0.5231, -2.2683,  0.0276]), res: -1.7175251245498657
tensor(-1.7175)
torch.Size([])


In [76]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
# t4 = torch.randn(3) # 이렇게는 브로드캐스팅 안됌. 마지막 차원에 맞춰야 하는 듯
t4 = torch.randn(4)
print(t3, t4, sep="\n")
print(torch.matmul(t3,t4))
print(torch.matmul(t3, t4).size())  # torch.Size([3])

tensor([[ 0.3125,  0.2971, -0.7993, -1.2179],
        [-0.4842,  1.1103,  0.0608, -0.0633],
        [-0.0388, -0.1641,  0.0297, -1.3805]])
tensor([ 0.6036,  1.2310,  0.8264, -1.4009])
tensor([1.6000, 1.2135, 1.7331])
torch.Size([3])


In [77]:
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
# t6 = torch.randn(3,4) # Error
# t6 = torch.randn(4,5) # OK
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

torch.Size([10, 3])


In [78]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


In [79]:
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


# i_tensor_broadcasting.py

In [80]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2


In [81]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3


In [82]:
def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [83]:
print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [84]:
'''
4칙연산 연산에 대해서는 broadcasting (o) 
단, 동일 차원의 맞지 않는 사이즈가 서로 배수관계여야 한다
'''

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [85]:
print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [86]:
print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing.py

In [87]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
) # size= (3,5)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [88]:
print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [89]:
print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [90]:
print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2]) #tensor([[1, 2, 3, 4], [2, 3, 4, 5]])
print(z[1:, 1:3]) #
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)


################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping.py

torch.tensor.view(size=(..))
torch.tensor.reshape(size=(..))

squeeze() : tensor의 모든 1차원 데이터를 flatten() 시킴
    즉, 1차원이 없도록 만듦.
    - squeeze(dim=N) : 특정 차원의 dimension이 1이면 차원 삭제 
    
unsqueeze(dim) : 특정 위치의 차원을 한번 감쌈 (squeeze의 반대) 

flatten() : 1차원 텐서로 만듦
    - torch.flatten(tensor, start_dim=#)
        start_dim = 이 인덱스를 기점으로 하위 차원의 값들을 flatten

permute() : 다차원 텐서의 차원을 일일히 지정하여 바꾸는 것

transpose(): 행과 열을 입력받아 두 차원을 바꿔주는 함수


In [91]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [92]:
print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [93]:
print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [94]:
print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)


################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [95]:
print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat.py

In [96]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape) # torch.Size([2, 6, 3])

torch.Size([2, 6, 3])


In [97]:
print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [98]:
print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [99]:
print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [100]:
print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking.py
torch.stack()

In [101]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2, 3
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]]) # 2, 3

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0) # 2,2,3
# cat((1,2,3), (1,2,3), dim=0) ==> (2,2,3)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
# cat((2, 1, 3), (2, 1, 3), dim=1) ==> (2,2,3)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
# cat((2,3,1), (2,3,1), dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [102]:
print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# n_tensor_vstack_hstack.py 

virtical VS horizontal

vstack : 최상위차원에 스택을 쌓는 느낌 
hstack : 상위 2번째 차원에 스택을 쌓는 느낌 ==> 모든 텐서가 동일한 행의 개수를 가져야함
(인자로 list 형식도 가능함)

In [103]:
import torch

t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.vstack((t1,t2))
print(t3)

t4 = torch.tensor([[1],[2],[3]]) # 3,1
t5 = torch.tensor([[4],[5],[6]]) # 3,1
t6 = torch.vstack((t4,t5))
print(t6)
t6 = torch.vstack([t4,t5])
print(t6)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [104]:
t7 = torch.tensor ([
[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]
])

print(t7.shape)

t8 = torch.tensor([
[[13, 14, 15], [16, 17, 18]],
[[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack ([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)
print(t9)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [105]:
import torch
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14)) # 3, 2
print(t15)
# >>> tensor([[1, 4],
# [2, 5],
# [3, 6]])

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [106]:
t16 = torch.tensor([
[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
[[13, 14, 15], [16, 17, 18]],
[[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1, 2, 3],
# [ 4, 5, 6],
# [13, 14, 15],
# [16, 17, 18]],
# [[ 7, 8, 9],
# [10, 11, 12],
# [19, 20, 21],
# [22, 23, 24]]])

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


In [107]:
m1 = torch.zeros([3,4,5,2])
m2 = torch.zeros([3,4,5,2])
res = torch.hstack([m1,m2])
print(res.shape)

torch.Size([3, 8, 5, 2])


-----------------------------------
# 숙제 후기

전에 numpy를 배운 적이 있지만 다 까먹었다. 교수님께서 numpy와 tensor가 비슷한 측면이 많다고 하셨는데, 여러모로 그런거 같다고 느꼈다. 

확실히 행렬이 들어가면서 선형대수학 시간에 배웠던 것들이 많이 보였다. 덕분에 과제를 수행하면서 내적과 외적의 의미를 다시한번 찾아보고 복습하는 계기가 되었다.

교수님께서 우리를 가르치실 때 이 많은 함수들을 모두 다 외우라고 시키시기 보다는 어떤 함수가 중요한 함수이고 어떤 부분이 중요한지를 짚어주셔서 공부하기에 한참 수월한 느낌을 받았다. 

비록 코드를 다 주셨지만 일일히 따라 쳐보면서 공부했더니 도움이 많이 되었다. 
예를 들어 size를 tuple로 넘겨주는 코드를 주로 보다가 
<code>torch.tensor([1,2,3])</code>
 같은 것을 보니 Size(3,) 짜리 텐서가 아닌 Size(1,2,3) 짜리 텐서로 생각하는 등의 헤프닝이 있었다.

하지만, 역설적이게도, 사실 나는 무작정 따라 치기보다는 머리로 이해하는 과정이 더욱 중요하다고 생각한다.